#@ load("@ytt:data", "data")
#@ load("@ytt:overlay", "overlay")

#@ secret_name = "private-registry-secret"

#! This Secret will be populated by secretgen-controller with the credentials
#! to authenticate with the container registry (if authentication is required).
---
apiVersion: v1
kind: Secret
metadata:
  name: #@ secret_name
  namespace: #@ data.values.namespace
  annotations:
    secretgen.carvel.dev/image-pull-secret: ""
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: e30K

#@overlay/match by=overlay.subset({"kind":"Deployment","metadata":{"namespace":data.values.namespace}}),expects="3+"
---
spec:
  template:
    spec:
      #@overlay/match missing_ok=True
      imagePullSecrets:
        - name: #@ secret_name
